version: "3"

services:
  api-server:
    build:
      context: ./
      dockerfile: api-server/Dockerfile
      target: development
    container_name: api-server
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - api-server/.env
    environment:
      - DB_HOST=postgres
    networks:
      - api-network
    
  # client:
  #   build:
  #     context: ./
  #     dockerfile: client/Dockerfile
  #     target: development
  #   container_name: client
  #   restart: unless-stopped
  #   volumes:
  #     - /app/node_modules
  #     - ./client:/app/client
  #   env_file:
  #     - client/.env
  #   ports:
  #     - "3001:3001"
  #   networks:
  #     - api-network
  
  postgres:
    build: 
      context: ./
      dockerfile: Dockerfile.postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=blindlyfading
    networks:
      - api-network


networks:
  api-network:
    driver: bridge